# Generated by Django 3.2.4 on 2021-06-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='log',
        ),
    ]
