# Generated by Django 3.2.4 on 2021-06-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_message_message_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='log',
            new_name='message',
        ),
    ]
