# Generated by Django 3.2.4 on 2021-06-19 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_log_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='alert',
            field=models.CharField(default='message whas created', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
