# Generated by Django 3.2.4 on 2021-06-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20210619_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='alert',
            field=models.CharField(default='message whas sended', max_length=200),
        ),
    ]
